[versions]
agp = "9.2.1"
kotlin = "2.4.+"
composeBom = "2026.08.00"
appcompat = "1.6.1"
coreKtx = "1.18.0"
junit = "4.13.2"
androidxJUnit = "1.3.0"
espressoCore = "3.7.0"
kotlinReflect = "2.0.21"
kotlinxCollectionsImmutable = "0.3.8"
kotlinxDatetime = "0.8.0"
activityCompose = "1.13.0"
mapsCompose = "8.3.0"
secretsGradlePlugin = "2.0.1"
navigation3 = "1.2.0-alpha04"
lifecycleViewmodel = "2.11.0-rc01"
mockk = "1.14.11"
uiautomator = "2.3.0"
datastore = "1.2.1"
kotlinxSerializationJson = "1.9.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }

[libraries]

secrets-plugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.1" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleViewmodel" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodel" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }

reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version = "3.1.0" }
kt-fuzzy = { module = "ca.solo-studios:kt-fuzzy", version = "0.1.0" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJUnit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockkandroid = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[bundles]
androidx-compose = [
    "androidx-compose-runtime",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    "androidx-compose-animation",
    "androidx-compose-animation-core",
    "androidx-compose-ui",
    "androidx-compose-ui-unit",
    "androidx-compose-ui-graphics",
    "androidx-compose-material3",
    "androidx-compose-material3-adaptive-navigation-suite",
]
androidx-compose-test = [
    "androidx-compose-ui-test",
    "androidx-compose-ui-test-junit4",
]
androidx-compose-tooling = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-ui-test-manifest",
]
androidx-navigation3 = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-lifecycle-viewmodel-navigation3",
]